export const PIECE_DROP_DURATION_MIN_SECONDS = 1.02;
export const PIECE_DROP_DURATION_MAX_SECONDS = 1.28;

export const COMPLETED_LINE_DRAW_DURATION_SECONDS = 1.35;
export const COMPLETED_LINE_SETTLE_DURATION_SECONDS = 0.45;

export const GAME_OVER_MODAL_DELAY_MS = Math.round(
	(COMPLETED_LINE_DRAW_DURATION_SECONDS + COMPLETED_LINE_SETTLE_DURATION_SECONDS + 0.28) * 1000
);
